/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as MusicTherapyRouteImport } from './routes/music-therapy'
import { Route as WhoWeServeRouteImport } from './routes/who-we-serve'
import { Route as ServicesIndexRouteImport } from './routes/services/index'
import { Route as ServicesAdaptiveMusicLessonsRouteImport } from './routes/services/adaptive-music-lessons'
import { Route as ServicesGroupTherapyRouteImport } from './routes/services/group-therapy'
import { Route as ServicesIndividualTherapyRouteImport } from './routes/services/individual-therapy'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const MusicTherapyRoute = MusicTherapyRouteImport.update({
  id: '/music-therapy',
  path: '/music-therapy',
  getParentRoute: () => rootRouteImport,
} as any)
const WhoWeServeRoute = WhoWeServeRouteImport.update({
  id: '/who-we-serve',
  path: '/who-we-serve',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesAdaptiveMusicLessonsRoute =
  ServicesAdaptiveMusicLessonsRouteImport.update({
    id: '/services/adaptive-music-lessons',
    path: '/services/adaptive-music-lessons',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesGroupTherapyRoute = ServicesGroupTherapyRouteImport.update({
  id: '/services/group-therapy',
  path: '/services/group-therapy',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndividualTherapyRoute =
  ServicesIndividualTherapyRouteImport.update({
    id: '/services/individual-therapy',
    path: '/services/individual-therapy',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/music-therapy': typeof MusicTherapyRoute
  '/who-we-serve': typeof WhoWeServeRoute
  '/services/adaptive-music-lessons': typeof ServicesAdaptiveMusicLessonsRoute
  '/services/group-therapy': typeof ServicesGroupTherapyRoute
  '/services/individual-therapy': typeof ServicesIndividualTherapyRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/music-therapy': typeof MusicTherapyRoute
  '/who-we-serve': typeof WhoWeServeRoute
  '/services/adaptive-music-lessons': typeof ServicesAdaptiveMusicLessonsRoute
  '/services/group-therapy': typeof ServicesGroupTherapyRoute
  '/services/individual-therapy': typeof ServicesIndividualTherapyRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/music-therapy': typeof MusicTherapyRoute
  '/who-we-serve': typeof WhoWeServeRoute
  '/services/adaptive-music-lessons': typeof ServicesAdaptiveMusicLessonsRoute
  '/services/group-therapy': typeof ServicesGroupTherapyRoute
  '/services/individual-therapy': typeof ServicesIndividualTherapyRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/music-therapy'
    | '/who-we-serve'
    | '/services/adaptive-music-lessons'
    | '/services/group-therapy'
    | '/services/individual-therapy'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/music-therapy'
    | '/who-we-serve'
    | '/services/adaptive-music-lessons'
    | '/services/group-therapy'
    | '/services/individual-therapy'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/music-therapy'
    | '/who-we-serve'
    | '/services/adaptive-music-lessons'
    | '/services/group-therapy'
    | '/services/individual-therapy'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  MusicTherapyRoute: typeof MusicTherapyRoute
  WhoWeServeRoute: typeof WhoWeServeRoute
  ServicesAdaptiveMusicLessonsRoute: typeof ServicesAdaptiveMusicLessonsRoute
  ServicesGroupTherapyRoute: typeof ServicesGroupTherapyRoute
  ServicesIndividualTherapyRoute: typeof ServicesIndividualTherapyRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/music-therapy': {
      id: '/music-therapy'
      path: '/music-therapy'
      fullPath: '/music-therapy'
      preLoaderRoute: typeof MusicTherapyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/who-we-serve': {
      id: '/who-we-serve'
      path: '/who-we-serve'
      fullPath: '/who-we-serve'
      preLoaderRoute: typeof WhoWeServeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/adaptive-music-lessons': {
      id: '/services/adaptive-music-lessons'
      path: '/services/adaptive-music-lessons'
      fullPath: '/services/adaptive-music-lessons'
      preLoaderRoute: typeof ServicesAdaptiveMusicLessonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/group-therapy': {
      id: '/services/group-therapy'
      path: '/services/group-therapy'
      fullPath: '/services/group-therapy'
      preLoaderRoute: typeof ServicesGroupTherapyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/individual-therapy': {
      id: '/services/individual-therapy'
      path: '/services/individual-therapy'
      fullPath: '/services/individual-therapy'
      preLoaderRoute: typeof ServicesIndividualTherapyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  MusicTherapyRoute: MusicTherapyRoute,
  WhoWeServeRoute: WhoWeServeRoute,
  ServicesAdaptiveMusicLessonsRoute: ServicesAdaptiveMusicLessonsRoute,
  ServicesGroupTherapyRoute: ServicesGroupTherapyRoute,
  ServicesIndividualTherapyRoute: ServicesIndividualTherapyRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
